### ISSUE TITLE
Issues with ampersand in company name

### ISSUE THREAD

**Issue by ghost** [jamesweakley/NCentralScreenConnectScripts#2]
HI there. I see the new script inputs a & into the sessiongroup.xml which causes screenconnect to not show the groups at all. It used to input &amp; which works fine but I cannot comit to the scripts as I am not sure what needs changing! Cheers!

**Comment by jamesweakley** [comment]
Looks like the new scripts don't apply any XML escaping (e.g. replace **&** with **&amp;**)

The old script used to do this: 
https://github.com/jamesweakley/NCentralScreenConnectScripts/blob/master/Session%20Group%20Sync/(old)GenerateScreenConnectSessionGroups_FromReportManager.ps1#L32
The same approach could be used in the new script, perhaps on this line:
https://github.com/jamesweakley/NCentralScreenConnectScripts/blob/master/Session%20Group%20Sync/GenerateScreenConnectSessionGroups.ps1#L178

**Comment by ghost** [comment]
Thanks James, seemed to do the trick!

**Comment by joncz** [comment]
Updated to include James' correction.
