### ISSUE TITLE
Encountering error with TellMeMyKey.aspx.cs

### ISSUE THREAD

**Issue by therealscottcarlow** [jamesweakley/NCentralScreenConnectScripts#3]
I encounter the following error when navigating to http://SC.domain.com/tellmemykey.aspx:

![image](https://cloud.githubusercontent.com/assets/12102631/21863610/08a7f1d2-d7f3-11e6-9522-1c2659d8916c.png)

I'm not super familiar with C#. Any ideas?

**Comment by therealscottcarlow** [comment]
I figured it out with some poking around. the typename `themeablepage` isn't part of the `Elsinore.ScreenConnect` namespace, it's part of the `Screenconnect` namespace. Now it works. I'll submit a PR.

**Comment by joncz** [comment]
Scott, you appear to have an old pull.  NCentralScreenConnectScripts/Client Install/InstallFromNCentralAgent.aspx.cs was updated in March, 2016 to address the changed namespace that ScreenConnect introduced with SC 5.0.

`namespace NCentral
{
    public partial class DownloadScreenConnect : ScreenConnect.ThemeablePage`

**Comment by joncz** [comment]
Thanks for pointing that out.  Updated.
